version: '3'

services:

  # NGINX reverse-proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports: [ "80:80", "443:443" ]
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-data/conf.d:/etc/nginx/conf.d
      - ./nginx-data/vhost.d:/etc/nginx/vhost.d
      - ./nginx-data/html:/usr/share/nginx/html
      - ./nginx-data/certs:/etc/nginx/certs:ro
      - ./nginx-data/htpasswd:/etc/nginx/htpasswd:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    environment:
      HTTPS_METHOD: "noredirect"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"

  # Automatically add SSL certificates from Let's Encrypt
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      # Uncoment to test on Staging
      #ACME_CA_URI: https://acme-staging.api.letsencrypt.org/directory
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx-data/conf.d:/etc/nginx/conf.d
      - ./nginx-data/vhost.d:/etc/nginx/vhost.d
      - ./nginx-data/html:/usr/share/nginx/html
      - ./nginx-data/certs:/etc/nginx/certs:rw
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - /root/.docker/config.json:/config.json # docker credentials
    command: --interval 60 --cleanup
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"

networks:
  default:
    external:
      name: certified